
name: Package

on: 
 workflow_dispatch:
    inputs:
      version:
        description: 'The version that will be used within this NuGet package'
        required: true
        default: '2.0.0'
jobs:              
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.100-preview.3.20216.6' # SDK Version to use.
      - name: Run Unit Tests
        run: |
            cd Twaddle/Twaddle.Library.Tests
            dotnet test --list-tests --configuration Release
            dotnet test --configuration Release
      - name: Package NuGet
        run: |
            cd Twaddle/Library/Twaddle.Library
            dotnet pack --configuration Release --include-symbols -p:PackageVersion=${{ github.event.inputs.version }}
             
            
    
